version: 2.1

jobs:
  unit-tests:
    docker:
      - image: python:3.11
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Run all tests 
          command: pytest tests/unit # automatically finds all test_*.py files in the relevant folder

workflows:
  version: 2
  build:
    jobs:
      - unit-tests
